### PR TITLE
LIME-66: Add svgr library

### LINKED ISSUE #66: Add svgr plugin
- [ ] add https://www.npmjs.com/package/vite-plugin-svgr
- [ ] use all SVG's as React components

### PR DESCRIPTION
**Pull request by ArtemLymarenko**
Added svgr library dependency. Also added icon component to extend default icons with className. Changed DropDown Icon in select component and LogoIcon in logoIcon component. Not sure how to replace existing folder icons to avoid confusion (supposed to be called custom-icons)

### CODE REVIEW

**Review by stpalamar — APPROVED** [review]

**Comment by SofiiaTrokhymchuk** [comment]
I think since icons are now used as components using svgr, Loader component can be refactored so that all the logic (including types) was moved from LogoIcon component to Loader component where new icon format is used. And therefore icons folder can be deleted (but before that we need to check if custom LogoIcon component is not used somewhere else besides Loader). You can try to do this by yourself to avoid logo icon duplication and confusion or I can create a branch from your branch and change it and then merge it into your branch once the changes are approved. What do you think?

**Comment by nikita-remeslov** [comment]
@SofiiaTrokhymchuk check this PR please :)

**Comment by SofiiaTrokhymchuk** [comment]
> @SofiiaTrokhymchuk check this PR please :)

What do you mean? :( I have already checked it (⊙_⊙)？

**Comment by ArtemLymarenko** [comment]
Colors and sizes were added to icon component. Icons folder was removed and loader was changed to use added styles. Also considered moving these styles to common enum folder.

**Comment by ArtemLymarenko** [comment]
After merging development in this branch, I noticed that David added icon for checkbox in **icons folder**. Since we agreed to remove this folder I'm wondering  can I move check-icon in checkbox component and remove the folder?

изображение

**Review by nikita-remeslov — APPROVED** [review]

**Pull request merged**
