### PR TITLE
LIME-67: Add pwa

### LINKED ISSUE #67: Add PWA
https://vite-pwa-org.netlify.app/

- [x] User should be able to download WEB app

### PR DESCRIPTION
**Pull request by jhladkov**

### CODE REVIEW

**Comment by jhladkov** [comment]
image

**Comment by jhladkov** [comment]
Added test images and icons for the first time

**Review by DavidCharif — APPROVED** [review]

**Review by dimapopovych — APPROVED** [review]

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]
I think we can use our website logo!

**Comment by jhladkov** [comment]
image

**Comment by jhladkov** [comment]
image

**Review by nikita-remeslov — APPROVED** [review]

**Pull request merged**
