### PR TITLE
LIME-4: Add tailwind colors theme

### LINKED ISSUE #2: Configure Tailwind colors theme
Configure Tailwind colors theme according to design 
Image
[Design](https://www.figma.com/file/RRE9g9LIo3a1AK89HBlN6U/BSA_Lime?type=design&node-id=0-1&mode=design)
[Docs](https://tailwindcss.com/docs/theme#colors)

### PR DESCRIPTION
**Pull request by SergiiTernytskyi**
Added tailwind colors theme

### CODE REVIEW

**Review by nikita-remeslov — COMMENTED** [review]
better to use prefix for colors to avoid conflicts with tailwind standard colors

`lm-red`
`lm-yellow`
etc.

**Comment by nikita-remeslov** [comment]
also link PR to the ticket, and unlink Project
image

**Comment by nikita-remeslov** [comment]
also ticket number in the naming incorrect 
image

**Comment by nikita-remeslov** [comment]
merge `development` branch please

**Review by nikita-remeslov — APPROVED** [review]

**Review by dimapopovych — APPROVED** [review]

**Pull request merged**
