### PR TITLE
LIME-259: FIX warnings

### LINKED ISSUE #259: Fix warnings
Fix warnings

Image

### PR DESCRIPTION
**Pull request by DavidCharif**
image

Comments are only on this image and do not appear on the request

### CODE REVIEW

**Comment by nikita-remeslov** [comment]
you PR include changes that no related to the ticket

**Comment by DavidCharif** [comment]
Before:
image

After:
image

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]
I am not sure that we need to use useMemo everywhere!

**Comment by nikita-remeslov** [comment]
we should rewrite selector 
image
 
and we don't need useMemo and reselect

**Pull request closed without merging**
