### PR TITLE
LIME-168:  Sign-up/Sign-in form vertically centered

### LINKED ISSUE #168: BUG: The components are not vertically centered on the Sign Up and Sign In pages
### Describe your issue

The components(labels, buttons and inputs) are not vertically centered on the Sign Up and Sign In pages 

### Steps to reproduce

1. Go to the [http://lime.eu-north-1.elasticbeanstalk.com/sign-in](http://lime.eu-north-1.elasticbeanstalk.com/sign-in)
2. Change the resolution to 1100x1200
3. Pay attention to the position of the buttons and inputs

### What was the actual result?

The components are not vertically centered on the Sign Up and Sign In pages

### What was the expected result?

The components are vertically centered on the Sign Up and Sign In pages

### Put here any screenshots or videos (optional)

Image

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

### PR DESCRIPTION
**Pull request by valery-chumak**

### CODE REVIEW

**Comment by valery-chumak** [comment]
image

**Comment by SergiiTernytskyi** [comment]
On application design the link to create an account is on the bottom of the page 
Screenshot_4

**Comment by valery-chumak** [comment]
@SergiiTernytskyi thanks for noticing) Looks like this now 
Снимок экрана 2024-02-24 153241

**Comment by stpalamar** [comment]
I think absolute positioning is not good idea because we can have offset like this when screen have small height
image

**Comment by valery-chumak** [comment]
> I think absolute positioning is not good idea because we can have offset like this when screen have small height image

I think I should wait when PR about [fix height responsivness](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/pull/176) will be merged to development to use his approach to handle the resizing of screen and fix this issue

**Review by dimapopovych — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]

**Pull request merged**
