### PR TITLE
LIME-70: + add component for Google Ads

### LINKED ISSUE #70: Add component for Google Ads
- [ ] It should be a responsive component. 
- [ ] Component can replace any element in the design.
- [ ] If there are no advertisements, the block should display “Your advertisement may be here”

Image

### PR DESCRIPTION
**Pull request by VasylynaKolodiy**
A component that adjusts to the width and height of the parent container.
It will be used to add it (advertisement) to any place on the site without breaking the layout.
screenshot-ads-1

### CODE REVIEW

**Review by dimapopovych — APPROVED** [review]

**Review by nikita-remeslov — COMMENTED** [review]
Maybe we can play little bit with styles for placeholder text

**Comment by nikita-remeslov** [comment]
example from our design 
image

**Comment by nikita-remeslov** [comment]
mb add some gradient 
image

**Comment by VasylynaKolodiy** [comment]
> mb add some gradient image

@nikita-remeslov ok, I will fix it

**Comment by VasylynaKolodiy** [comment]
> mb add some gradient image

After changing styles:

screenshot-ads-4

**Review by nikita-remeslov — APPROVED** [review]

**Pull request merged**
