### PR TITLE
LIME-195: Fixed modal window styles

### LINKED ISSUE #195: BUG: Width of the elements of the modal window for Password Reset doesn't correspond to the width of the modal
### Describe your issue

When changing the width of browser window, the width of Email field is minimized and label of the form is situated on 5 lines with enough width of modal window left 

### Steps to reproduce

1. Open Sign In page
2. Click on Forgot Password?
3. Minimize the window of browser, changing it's width
4. Pay attention to the responsiveness of the modal window and it's elements

### What was the actual result?

With enough width of modal window, the width of Email field is minimized and label of the form is situated on 5 lines

### What was the expected result?

If there's enough width of modal window, the width of Email field is not minimized and label of the form is situated on the minimum possible number of lines

### Put here any screenshots or videos (optional)

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/5068d41b-619c-4783-a115-d5dcb6395b04

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

### PR DESCRIPTION
**Pull request by SergiiTernytskyi**
Fixed modal window styles

### CODE REVIEW

**Comment by stpalamar** [comment]
Can you add screenshots?

**Comment by SergiiTernytskyi** [comment]
https://www.loom.com/share/b62a0ab896a54c87a44cb470ba7c1825

**Comment by stpalamar** [comment]
I think we can add small margin for modal and make padding inside smaller. As for me, it will looks better
image

**Comment by SergiiTernytskyi** [comment]
modal

**Review by stpalamar — APPROVED** [review]

**Review by ArtemLymarenko — APPROVED** [review]

**Review by valery-chumak — APPROVED** [review]

**Review by anton-otroshchenko — APPROVED** [review]

**Pull request merged**
