### PR TITLE
LIME-250: Fix connections page

### LINKED ISSUE #250: Fix connections page adaptivity
Fix connections page adaptivity

### PR DESCRIPTION
**Pull request by ArtemLymarenko**
I fixed problems with connections page and changed responsivness. But we have some issues on small screens.

изображение
изображение

Side bar is very wide I think maybe it'll be good solution to create burger button on all the types of screens.
изображение

изображение

Also unclear what to do with subnavigation menu on small screens
изображение

### CODE REVIEW

**Comment by stpalamar** [comment]
We need to figure out how we can hide sub-navigation component on smaller screens. Another hamburger menu or maybe some other way?

**Comment by SofiiaTrokhymchuk** [comment]
I also had this question about subnav. I think we can leave it as it is in those tickets that use subnav but create a separate ticket to add responsiveness. Maybe we can have like narrow subnav with just options and icons instead of text with the ability to expand the subnav to wide version with text and not to hide it completely with a burger. What do you guys think?

**Comment by valery-chumak** [comment]
Maybe we should make a subnavigation menu narrower and for example instead of text with icons put only icons which can represent our sub menu points. For example, for personal info make a user icon, for connection like a network icon. Just an idea)

**Comment by ArtemLymarenko** [comment]
Good points guys

**Comment by stpalamar** [comment]
I like idea with icons and ability to expand. 
What about workouts page? 
Originally, I thought that will be like history of workouts because we have this "add workout" button in the design. Like one item is one separate workout. 
But I guess I was wrong) So, it is only tabs for each activity type and we can use icon for each type of activity, is it?
image

**Comment by ArtemLymarenko** [comment]
I think in this case yes, we can try it.

**Comment by SofiiaTrokhymchuk** [comment]
No, you were right. Each item in subnav leads to unique separate workout

**Comment by stpalamar** [comment]
Ohh, so icons is not a solution for workouts. We need different layout for mobile screens in workout page. Maybe we can show sub-navigation with list of user workout in fullscreen on small screens?

**Comment by SofiiaTrokhymchuk** [comment]
Guys I have a question. Do these links lead to list of all workouts of a specific type or to a unique workout?

**Comment by stpalamar** [comment]
Or even better doesn't use sub-navigation on smaller screens. We can create new component like **workout card** with brief information of workout and show list of these cards on small screens. And if user needs more information of workout he can click on this card and navigate to page with certain workout.

**Comment by stpalamar** [comment]
But I'm not sure about this list of workouts anyway. It can be just link to workouts of specific type. We should clarify this moment with coaches and others. And maybe move this discussion to slack because it is not related to PR :)

**Review by nikita-remeslov — APPROVED** [review]

**Pull request merged**
